"""M8e: the register model end-to-end, integrated and simulated.

Wires three generated pieces into one system and proves the full data path:

    bus write to a watched register  ->  regblock `ws_changed` pulse  ->  engine
    FSM wakes (wait-beat) and reacts (increments a count output).

  - the regblock RTL is generated by the register-model emitter (with a watch-set
    change pulse), exactly as in M6/M7;
  - the engine FSM is produced by the real SPL->RTL lowering (the wait-beat), then
    emitted by be_sv -- i.e. the same path the front end will drive;
  - a top module wires `regblock.ws_changed -> engine.set_changed`.

The engine's SPL is built here (standing in for the front end's SV->SPL output,
which is the remaining generalization); everything downstream is the real flow.
"""
import subprocess
from pathlib import Path

import pytest
import zuspec.ir.core as ir

from fw.hdl import ir_build as b
from fw.hdl.config import FlowConfig
from fw.hdl.errors import ErrorReporter
from fw.hdl.lower.spl2rtl import lower_context
from fw.hdl.emit.be_sv import emit_sv
from fw.hdl.emit.regblock import emit_regblock
from fw.hdl.regmap import RegBlock, Register, RegField, RegUsage

REPO = Path(__file__).resolve().parents[3]
VERILATOR = REPO / "packages" / "verilator" / "bin" / "verilator"


def _regblock_sv():
    ctrl = Register("ctrl", 0x0, 32, sw_wmask=0x1, fields=[
        RegField("go", 0, 1, sw_write=True, hw_write=False, rclr=False)])
    spare = Register("spare", 0x4, 32, sw_wmask=0xffffffff, fields=[
        RegField("val", 0, 32, sw_write=True, hw_write=False, rclr=False)])
    blk = RegBlock("reg_dev", registers=[ctrl, spare], size=0x8)
    # watch-set over ctrl -> ws_changed pulses on a software write to ctrl
    return emit_regblock(blk, usage=RegUsage(change_sets={"ws": [0x0]}))


def _engine_sv():
    """forever { wait_until(set_changed); count = count + 1 } -> an FSM that counts
    change pulses; the same shape the engine arbiter's wait_change loop lowers to."""
    i1 = ir.DataTypeInt(bits=1, signed=False)
    clock = ir.FieldInOut(name="clock", datatype=i1, is_out=False)
    clock.pragmas.update({"fw_role": "clock"})
    reset = ir.FieldInOut(name="reset", datatype=i1, is_out=False)
    reset.pragmas.update({"fw_role": "reset"})
    set_changed = ir.FieldInOut(name="set_changed", datatype=i1, is_out=False)
    count = ir.FieldInOut(name="count", datatype=ir.DataTypeInt(bits=8, signed=False),
                          is_out=True)
    sref = lambda i: ir.ExprRefField(base=ir.TypeExprRefSelf(), index=i)
    wait = lambda c: ir.StmtExpr(expr=ir.ExprAwait(value=ir.ExprCall(
        func=ir.ExprAttribute(value=ir.TypeExprRefSelf(), attr="wait_until"),
        args=[c], keywords=[])))
    loop = ir.StmtWhile(test=ir.ExprConstant(value=True), body=[
        wait(sref(2)),                                          # wait_change
        ir.StmtAssign(targets=[sref(3)],
                      value=ir.ExprBin(lhs=sref(3), op=ir.BinOp.Add,
                                       rhs=ir.ExprConstant(value=1))),
    ], orelse=[])
    run = ir.Function(name="run", body=[loop], is_async=True)
    comp = b.component("engine", [clock, reset, set_changed, count],
                       proc_processes=[run])
    rep = ErrorReporter()
    rtl = lower_context(b.context([comp]), FlowConfig(), rep)
    assert rtl is not None, rep.report()
    return emit_sv(rtl)


_TOP = """
module top (
  input  logic        clock,
  input  logic        reset,
  input  logic [2:0]  s_addr,
  input  logic        s_wr,
  input  logic [31:0] s_wdata,
  input  logic        s_rd,
  output logic [31:0] s_rdata,
  output logic [7:0]  count
);
  logic ws_changed;
  reg_dev_regblock rb (
    .clock, .reset, .s_addr, .s_wr, .s_wdata, .s_rd, .s_rdata, .ws_changed);
  engine eng (.clock, .reset, .set_changed(ws_changed), .count);
endmodule
"""

_TB = """
module tb;
  logic clock = 0, reset = 1; always #5 clock = ~clock;
  logic [2:0]  s_addr = 0; logic s_wr = 0, s_rd = 0;
  logic [31:0] s_wdata = 0, s_rdata; logic [7:0] count;
  top dut (.clock, .reset, .s_addr, .s_wr, .s_wdata, .s_rd, .s_rdata, .count);
  int errors = 0;
  task automatic chk(bit c, string m); if (!c) begin $display("FAIL: %s", m); errors++; end endtask

  // one software write to ctrl (the watched register) -> one ws_changed pulse
  task automatic write_ctrl();
    @(posedge clock); s_addr <= 3'h0; s_wdata <= 32'h1; s_wr <= 1;
    @(posedge clock); s_wr <= 0;
  endtask
  // a write to the unwatched register must NOT wake the engine
  task automatic write_spare();
    @(posedge clock); s_addr <= 3'h4; s_wdata <= 32'h5; s_wr <= 1;
    @(posedge clock); s_wr <= 0;
  endtask

  initial begin
    repeat (3) @(posedge clock); reset = 0; @(posedge clock);
    chk(count === 8'd0, "count starts 0");

    write_ctrl(); repeat (2) @(posedge clock);
    chk(count === 8'd1, "ctrl write -> engine counted 1");

    write_spare(); repeat (2) @(posedge clock);
    chk(count === 8'd1, "spare write -> engine NOT woken");

    write_ctrl(); write_ctrl(); write_ctrl(); repeat (2) @(posedge clock);
    chk(count === 8'd4, "three more ctrl writes -> count 4");

    if (errors == 0) $display("[engine_regblock] PASS");
    else             $display("[engine_regblock] FAIL (%0d errors)", errors);
    $finish;
  end
  initial begin #20000; $display("[engine_regblock] TIMEOUT"); $finish; end
endmodule
"""


@pytest.mark.skipif(not VERILATOR.exists(), reason="verilator not available")
def test_engine_reacts_to_regblock_change(tmp_path):
    (tmp_path / "rb.sv").write_text(_regblock_sv())
    (tmp_path / "engine.sv").write_text(_engine_sv())
    (tmp_path / "top.sv").write_text(_TOP)
    (tmp_path / "tb.sv").write_text(_TB)

    build = subprocess.run(
        [str(VERILATOR), "--binary", "--timing", "-j", "0", "-Wno-fatal",
         "--top-module", "tb", "-o", "simv", "rb.sv", "engine.sv", "top.sv", "tb.sv"],
        cwd=tmp_path, capture_output=True, text=True)
    assert build.returncode == 0, build.stdout + build.stderr
    run = subprocess.run([str(tmp_path / "obj_dir" / "simv")],
                         cwd=tmp_path, capture_output=True, text=True)
    assert "[engine_regblock] PASS" in run.stdout, run.stdout + run.stderr
