"""The call API of SV components -- procs (xls-examples.md G-9 for procs, E9).

The function API (fn_api) gives a test one task per function. A component's
API gives it one task per port, named after the port:

    a port the component gets from (its input)   ->  task <port>_put(input T v)
    a port the component puts to (its output)    ->  task <port>_get(output T v)

A test puts stimulus on the inputs and gets results from the outputs, as a
DSLX #[test_proc] sends on and receives from the proc's channels. As for
functions, the test holds the API and each level supplies a module named
`<api>_harness` that binds it:

    <api>_pkg.sv     (Components)     an interface class per component, the
                                      proxies tests get, bind functions
    <api>_model.sv   (ModelBinding)   the SV components on the fw-hdl runtime,
                                      their ports on queues
    <api>_xls.sv     (XlsBinding)     the XLS modules, each channel driven or
                                      collected on its ready/valid pins

Put queues the value; get waits until there is one. So a test can put a whole
stimulus and then get the results, or interleave the two. At `model`, a
component's own put waits until the test has taken the value (a rendezvous),
so a component that never blocks on input -- one that polls -- cannot run
ahead without bound.
"""
from __future__ import annotations

import dataclasses as dc
import json
import re
from typing import Dict, List, Optional

COMP_FORMAT = "fw.hdl.comp-api"


@dc.dataclass
class CompPort:
    name: str
    role: str        # "put" (the component's input) or "get" (its output)
    type: str        # SV payload type, as spelled inside its package (Spec::T)
    bits: int
    nb: bool = False # the component polls this input (fw_get_nb_if)


@dc.dataclass
class CompApi:
    name: str            # the component class or typedef spelling: RunLengthEncoder32
    sv: str              # package-qualified: rle_pkg::RunLengthEncoder32
    module: str          # the XLS module: rle_pkg__RunLengthEncoder32 (as fw.hdl.xls.IR names it)
    ports: List[CompPort]


@dc.dataclass
class CompApiSet:
    name: str            # the API package's name: rle_pkg_api
    components: List[CompApi]
    sources: List[str] = dc.field(default_factory=list)

    @property
    def pkg(self) -> str:
        return f"{self.name}_pkg"

    def imports(self) -> List[str]:
        """The components' packages. Generated code imports them and spells a
        payload type `Spec::T`: Verilator does not take `pkg::Spec::T`."""
        return list(dict.fromkeys(c.sv.split("::")[0] for c in self.components
                                  if "::" in c.sv))

    def save(self, path: str):
        with open(path, "w") as f:
            json.dump({"format": COMP_FORMAT, **dc.asdict(self)}, f, indent=2)

    @staticmethod
    def load(path: str) -> "CompApiSet":
        with open(path) as f:
            d = json.load(f)
        if d.get("format") != COMP_FORMAT:
            raise ValueError(f"{path}: not a {COMP_FORMAT} file")
        comps = [CompApi(c["name"], c["sv"], c["module"],
                         [CompPort(**p) for p in c["ports"]]) for c in d["components"]]
        return CompApiSet(d["name"], comps, d.get("sources", []))


def ident(spelling: str) -> str:
    return re.sub(r"\W", "_", spelling.replace("::", "__"))


_HEADER = "// Generated by {task}. Do not edit.\n"


# ----------------------------------------------------------------------
# The API package
# ----------------------------------------------------------------------

def _task(p: CompPort) -> str:
    d = "input" if p.role == "put" else "output"
    return f"task {p.name}_{p.role}({d} {p.type} v)"


def api_pkg_sv(api: CompApiSet) -> str:
    o = [_HEADER.format(task="fw.hdl.api.Components"), f"package {api.pkg};"]
    o += [f"    import {p}::*;" for p in api.imports()] + [""]
    for c in api.components:
        n = f"{ident(c.name)}_api"
        o += [f"    // {c.sv}: one task per port.",
              f"    interface class {n};"]
        o += [f"        pure virtual {_task(p)};" for p in c.ports]
        o += ["    endclass", "",
              f"    class {n}_proxy implements {n};",
              f"        static {n} impl;"]
        for p in c.ports:
            o += [f"        virtual {_task(p)};",
                  "            if (impl == null) #1;   // the binding registers at time 0",
                  "            if (impl == null)",
                  f"                $fatal(1, \"{n}: no binding; the test bench needs a "
                  f"{api.name}_harness\");",
                  f"            impl.{p.name}_{p.role}(v);",
                  "        endtask"]
        o += ["    endclass", "",
              # Not named after the component: that name is the component's
              # type (imported), and a function of the same name would hide it.
              f"    function automatic {n} get_{ident(c.name)}();",
              f"        {n}_proxy p = new();",
              "        return p;",
              "    endfunction", "",
              f"    function automatic void bind_{ident(c.name)}({n} impl);",
              f"        {n}_proxy::impl = impl;",
              "    endfunction", ""]
    o += ["endpackage", ""]
    return "\n".join(o)


# ----------------------------------------------------------------------
# The model binding: the SV components on the fw-hdl runtime
# ----------------------------------------------------------------------

def model_harness_sv(api: CompApiSet) -> str:
    """Each component under a root component; each port bound to a queue. A
    put pushes on its port's queue, which the component gets from; the
    component's puts land on a queue a get pops."""
    o = [_HEADER.format(task="fw.hdl.api.ModelBinding"),
         "// Level `model`: the SV components answer, on the fw-hdl runtime.",
         '`include "fw_std_macros.svh"',
         f"module {api.name}_harness;",
         "    import fw_hdl_pkg::*;",
         "    import fw_std_pkg::*;"]
    o += [f"    import {p}::*;" for p in api.imports()] + [""]
    for c in api.components:
        cid = ident(c.name)
        for p in c.ports:
            if p.role == "put":
                iface = "fw_get_nb_if" if p.nb else "fw_get_if"
                o += [f"    class {cid}_{p.name}_src implements {iface} #({p.type});",
                      f"        {p.type} q[$];",
                      f"        virtual task get(output {p.type} t);",
                      "            wait (q.size() > 0);",
                      "            t = q.pop_front();",
                      "        endtask"]
                if p.nb:
                    o += [f"        virtual function bit try_get(inout {p.type} t);",
                          "            if (q.size() == 0) return 1'b0;",
                          "            t = q.pop_front();",
                          "            return 1'b1;",
                          "        endfunction"]
                o += ["    endclass"]
            else:
                # A rendezvous: the component's put returns once the test
                # has taken the value.
                o += [f"    class {cid}_{p.name}_snk implements fw_put_if #({p.type});",
                      f"        {p.type} q[$];",
                      "        longint unsigned n_put, n_taken;",
                      f"        virtual task put(input {p.type} t);",
                      "            longint unsigned seq;",
                      "            q.push_back(t);",
                      "            seq = ++n_put;",
                      "            wait (n_taken >= seq);",
                      "        endtask",
                      "    endclass"]
        o += [f"    class {cid}_model implements {api.pkg}::{cid}_api;"]
        for p in c.ports:
            kind = "src" if p.role == "put" else "snk"
            o.append(f"        {cid}_{p.name}_{kind} {p.name};")
        for p in c.ports:
            if p.role == "put":
                o += [f"        virtual {_task(p)};", f"            {p.name}.q.push_back(v);",
                      "        endtask"]
            else:
                o += [f"        virtual {_task(p)};",
                      f"            wait ({p.name}.q.size() > 0);",
                      f"            v = {p.name}.q.pop_front();",
                      f"            {p.name}.n_taken++;", "        endtask"]
        o += ["    endclass", ""]
    o += [f"    class {api.name}_top extends fw_component;"]
    for c in api.components:
        cid = ident(c.name)
        o.append(f"        {c.sv} {cid}_dut;")
        o.append(f"        {cid}_model {cid}_m = new;")
        for p in c.ports:
            iface = ("fw_get_nb_if" if p.nb else "fw_get_if") if p.role == "put" else "fw_put_if"
            o.append(f"        fw_export #({iface} #({p.type})) {cid}_{p.name}_e;")
    o += ["        function new(string name, fw_component parent);",
          "            super.new(name, parent);", "        endfunction",
          "        function void build();"]
    for c in api.components:
        cid = ident(c.name)
        o.append(f'            {cid}_dut = new("{cid}", this);')
        for p in c.ports:
            kind = "src" if p.role == "put" else "snk"
            o += [f"            {cid}_m.{p.name} = new;",
                  f'            {cid}_{p.name}_e = new("{cid}_{p.name}_e", this, '
                  f"{cid}_m.{p.name});"]
    o += ["        endfunction", "        function void connect();"]
    for c in api.components:
        cid = ident(c.name)
        o += [f"            {cid}_dut.{p.name}.connect({cid}_{p.name}_e);" for p in c.ports]
    o += ["        endfunction", "    endclass", "",
          "    bit clock = 1'b0, reset = 1'b0;",
          "    fw_clock_xtor_if u_clk(.clock(clock), .reset(reset));",
          f"    fw_component_root #({api.name}_top) top;",
          "    initial begin",
          "        automatic fw_clock_xtor_bridge clk_dom;",
          '        top = new("top");',
          '        clk_dom = new("clock", top, u_clk);',
          "        top.clock.connect(clk_dom);"]
    for c in api.components:
        cid = ident(c.name)
        o.append(f"        {api.pkg}::bind_{cid}(top.{cid}_m);")
    o += ["        fork top.start(); join_none", "    end", "endmodule", ""]
    return "\n".join(o)


# ----------------------------------------------------------------------
# The XLS binding: each channel on its ready/valid pins
# ----------------------------------------------------------------------

def xls_binding_sv(api: CompApiSet, sigs: Dict[str, object], period: int = 10,
                   reset_cycles: int = 4, timeout_cycles: int = 100000) -> str:
    """*sigs*: module name -> zuspec BlockSignature (from the XLS signature)."""
    n = api.name
    o = [_HEADER.format(task="fw.hdl.api.XlsBinding"),
         "// Level `rtl` (and `gates`): the XLS modules answer. Each input channel",
         "// presents queued values with its valid; each output channel is always",
         "// ready and queues what it receives. Port names come from the signatures.",
         ""]
    for c in api.components:
        sig = sigs[c.module]
        o.append(f"interface {c.module}_xtor_if (input bit clk, input bit rst);")
        chans = {ch.name: ch for ch in sig.channels}
        for p in c.ports:
            ch = chans.get(p.name)
            if ch is None:
                raise ValueError(f"{c.module}: no channel {p.name!r} in the XLS signature "
                                 f"(has {sorted(chans)})")
            w = ch.payload.bits
            if w != p.bits:
                raise ValueError(f"{c.module}.{p.name}: {w} bits in XLS, {p.bits} in SV")
            o += [f"    bit [{w - 1}:0] {ch.ports['data']};",
                  f"    bit {ch.ports['valid']};",
                  f"    bit {ch.ports['ready']};",
                  f"    bit [{w - 1}:0] q_{p.name}[$];"]
        o += ["", "    always @(posedge clk) begin", "        if (rst) begin"]
        for p in c.ports:
            ch = chans[p.name]
            if p.role == "put":
                o.append(f"            {ch.ports['valid']} <= 1'b0;")
            else:
                o.append(f"            {ch.ports['ready']} <= 1'b0;")
        o += ["        end else begin"]
        for p in c.ports:
            ch = chans[p.name]
            d, v, r = ch.ports["data"], ch.ports["valid"], ch.ports["ready"]
            if p.role == "put":
                o += [f"            // {p.name}: drop the value just taken; present the next.",
                      f"            if ({v} && {r}) void'(q_{p.name}.pop_front());",
                      f"            if (q_{p.name}.size() != 0) begin",
                      f"                {v} <= 1'b1;",
                      f"                {d} <= q_{p.name}[0];",
                      "            end else begin",
                      f"                {v} <= 1'b0;",
                      "            end"]
            else:
                o += [f"            // {p.name}: always ready; keep what arrives.",
                      f"            {r} <= 1'b1;",
                      f"            if ({v} && {r}) q_{p.name}.push_back({d});"]
        o += ["        end", "    end", ""]
        for p in c.ports:
            if p.role == "put":
                o += [f"    task automatic {p.name}_put(input bit [{p.bits - 1}:0] v);",
                      f"        q_{p.name}.push_back(v);", "    endtask"]
            else:
                o += [f"    task automatic {p.name}_get(output bit [{p.bits - 1}:0] v);",
                      f"        while (q_{p.name}.size() == 0) @(posedge clk);",
                      f"        v = q_{p.name}.pop_front();", "    endtask"]
        o += ["endinterface", ""]

    o += [f"package {n}_xls_pkg;"]
    o += [f"    import {p}::*;" for p in api.imports()]
    for c in api.components:
        cid = ident(c.name)
        o += [f"    class {cid}_xls implements {api.pkg}::{cid}_api;",
              f"        virtual {c.module}_xtor_if vif;"]
        for p in c.ports:
            o += [f"        virtual {_task(p)};", f"            vif.{p.name}_{p.role}(v);",
                  "        endtask"]
        o += ["    endclass"]
    o += ["endpackage", ""]

    o += [f"module {n}_harness;",
          "    bit clk = 1'b0;",
          "    bit rst = 1'b1;",
          f"    always #{period // 2} clk = ~clk;",
          "    initial begin",
          f"        repeat ({reset_cycles}) @(posedge clk);",
          "        rst <= 1'b0;",
          "    end", ""]
    if timeout_cycles:
        o += ["    initial begin",
              f"        repeat ({timeout_cycles}) @(posedge clk);",
              f"        $fatal(1, \"{n}_harness: timeout after {timeout_cycles} cycles\");",
              "    end", ""]
    for c in api.components:
        sig = sigs[c.module]
        cid = ident(c.name)
        o.append(f"    {c.module}_xtor_if {cid}_if (.clk(clk), .rst(rst));")
        conns = [f".{sig.clock or 'clk'}(clk)"]
        if sig.reset:
            conns.append(f".{sig.reset}({'!rst' if sig.reset_active_low else 'rst'})")
        for ch in sig.channels:
            conns += [f".{ch.ports[r]}({cid}_if.{ch.ports[r]})" for r in ("data", "valid", "ready")]
        o += [f"    {c.module} u_{cid} (", "        " + ",\n        ".join(conns), "    );", ""]
    o += ["    initial begin"]
    # Declarations first: a block's declarations precede its statements.
    o += [f"        automatic {n}_xls_pkg::{ident(c.name)}_xls x_{ident(c.name)} = new();"
          for c in api.components]
    for c in api.components:
        cid = ident(c.name)
        o += [f"        x_{cid}.vif = {cid}_if;",
              f"        {api.pkg}::bind_{cid}(x_{cid});"]
    o += ["    end", "endmodule", ""]
    return "\n".join(o)
