"""The call API of SV functions (xls-examples.md G-9, TB-2).

A test calls a design through an API: an interface class with one task per
exported function. The test holds the API, never a binding, so the same test
runs at every level:

    <api>_pkg.sv     (Functions)     interface class <api>, the proxy a test
                                     gets from <api>_pkg::get(), and <api>_model,
                                     which calls the SV function
    <api>_model.sv   (ModelBinding)  module <api>_harness: binds <api>_model
    <api>_xls.sv     (XlsBinding)    per function, a transactor interface on the
                                     XLS module's pins; the bridge class; module
                                     <api>_harness: clock, reset, the modules,
                                     and the bridge bound as the API

Each level supplies a module named `<api>_harness`, so the test bench that
instantiates it never changes. The binding is registered at time 0; the proxy
waits one time step for it on a first call.

A task, not a function, because a call takes time when RTL answers it.
"""
from __future__ import annotations

import dataclasses as dc
import json
import re
from typing import Dict, List, Optional, Sequence

from pyslang import ast

API_FORMAT = "fw.hdl.fn-api"
API_VERSION = 1


@dc.dataclass
class ApiArg:
    name: str
    #: SV type, as declared (package-qualified): `bit[7:0]`, `crc32_pkg::digest_t`.
    type: str
    #: Unpacked dimensions, as a declarator suffix (`[0:7]`); empty for none.
    dims: str = ""
    bits: int = 0
    signed: bool = False

    def decl(self, name: Optional[str] = None) -> str:
        return f"{self.type} {name or self.name}{self.dims}"


@dc.dataclass
class ApiFn:
    name: str            # the SV function's name: the API task's name
    path: str            # its hierarchical path: crc32_pkg::main
    module: str          # the module XLS makes of it: crc32_pkg__main
    args: List[ApiArg]
    ret: ApiArg          # name "result"


@dc.dataclass
class FnApi:
    name: str            # crc32_pkg_api
    functions: List[ApiFn]
    sources: List[str] = dc.field(default_factory=list)

    @property
    def pkg(self) -> str:
        return f"{self.name}_pkg"

    def save(self, path: str):
        with open(path, "w") as f:
            json.dump({"format": API_FORMAT, "version": API_VERSION, **dc.asdict(self)},
                      f, indent=2)

    @staticmethod
    def load(path: str) -> "FnApi":
        with open(path) as f:
            d = json.load(f)
        if d.get("format") != API_FORMAT:
            raise ValueError(f"{path}: not a {API_FORMAT} file")
        fns = [ApiFn(f["name"], f["path"], f["module"], [ApiArg(**a) for a in f["args"]],
                     ApiArg(**f["ret"])) for f in d["functions"]]
        return FnApi(d["name"], fns, d.get("sources", []))


# ----------------------------------------------------------------------
# From the SV
# ----------------------------------------------------------------------

def _arg(name: str, t) -> ApiArg:
    dims = ""
    while t.isUnpackedArray:
        ct = t.canonicalType
        if ct.kind != ast.SymbolKind.FixedSizeUnpackedArrayType:
            raise ValueError(f"{name}: only fixed-size unpacked arrays can cross the API")
        dims += f"[{ct.range.left}:{ct.range.right}]"
        t = ct.elementType
    return ApiArg(name=name, type=str(t), dims=dims, bits=int(t.bitWidth),
                  signed=bool(t.isSigned))


def api_from_subroutines(name: str, subs, module_of) -> FnApi:
    fns = []
    for s in subs:
        args = [_arg(a.name, a.type) for a in s.arguments]
        fns.append(ApiFn(name=s.name, path=s.hierarchicalPath, module=module_of(s),
                         args=args, ret=_arg("result", s.returnType)))
    names = [f.name for f in fns]
    dup = sorted({n for n in names if names.count(n) > 1})
    if dup:
        raise ValueError(f"API {name}: two functions named {dup}; an API task "
                         f"needs a unique name")
    return FnApi(name=name, functions=fns)


def default_api_name(paths: Sequence[str]) -> str:
    """`crc32_pkg::main` -> `crc32_pkg_api`: the first function's scope."""
    scope = paths[0].rsplit("::", 1)[0] if "::" in paths[0] else paths[0]
    return re.sub(r"\W", "_", scope.replace("::", "__")) + "_api"


# ----------------------------------------------------------------------
# SV text
# ----------------------------------------------------------------------

def _task_sig(f: ApiFn) -> str:
    args = [f"input {a.decl()}" for a in f.args] + [f"output {f.ret.decl()}"]
    return f"task {f.name}({', '.join(args)})"


def _call_args(f: ApiFn) -> str:
    return ", ".join([a.name for a in f.args] + ["result"])


_HEADER = "// Generated by {task} from {src}. Do not edit.\n"


def api_pkg_sv(api: FnApi) -> str:
    n = api.name
    fns = api.functions
    o = [_HEADER.format(task="fw.hdl.api.Functions", src=", ".join(api.sources) or "SV"),
         f"package {api.pkg};", "",
         f"    // The call API: one task per function. A test holds an {n}",
         "    // and does not know which level answers it.",
         f"    interface class {n};"]
    o += [f"        pure virtual {_task_sig(f)};" for f in fns]
    o += ["    endclass", "",
          "    // What get() returns: forwards each call to the binding the level",
          "    // registered with bind_api().",
          f"    class {n}_proxy implements {n};",
          f"        static {n} impl;", ""]
    for f in fns:
        o += [f"        virtual {_task_sig(f)};",
              "            if (impl == null) #1;   // the binding registers at time 0",
              "            if (impl == null)",
              f"                $fatal(1, \"{n}: no binding; the test bench needs a {n}_harness\");",
              f"            impl.{f.name}({_call_args(f)});",
              "        endtask"]
    o += ["    endclass", "",
          f"    function automatic {n} get();",
          f"        {n}_proxy p = new();",
          "        return p;",
          "    endfunction", "",
          f"    function automatic void bind_api({n} impl);",
          f"        {n}_proxy::impl = impl;",
          "    endfunction", "",
          "    // The model binding: each call runs the SV function itself.",
          f"    class {n}_model implements {n};"]
    for f in fns:
        o += [f"        virtual {_task_sig(f)};",
              f"            result = {f.path}({', '.join(a.name for a in f.args)});",
              "        endtask"]
    o += ["    endclass", "", "endpackage", ""]
    return "\n".join(o)


def model_harness_sv(api: FnApi) -> str:
    n = api.name
    return "\n".join([
        _HEADER.format(task="fw.hdl.api.ModelBinding", src=f"{n}"),
        f"// Level `model`: the API is answered by the SV functions.",
        f"module {n}_harness;",
        "    initial begin",
        f"        automatic {api.pkg}::{n}_model m = new();",
        f"        {api.pkg}::bind_api(m);",
        "    end",
        "endmodule", ""])


# ----------------------------------------------------------------------
# The XLS binding
# ----------------------------------------------------------------------

@dc.dataclass
class FnModule:
    """What the binding needs from XLS's ModuleSignatureProto of a function."""
    module: str
    inputs: List[tuple]          # (port, width), in order
    output: tuple                # (port, width)
    clock: str
    reset: Optional[str]
    reset_active_low: bool
    latency: int
    input_valid: Optional[str]
    output_valid: Optional[str]


def fn_module_from_signature(text: str) -> FnModule:
    from zuspec.be.xls.signature import parse_textproto, _one
    sig = parse_textproto(text)
    ins, outs = [], []
    for p in sig.get("data_ports", []):
        port = (_one(p, "name"), int(_one(p, "width")))
        (ins if _one(p, "direction") == "PORT_DIRECTION_INPUT" else outs).append(port)
    if len(outs) != 1:
        raise ValueError(f"{_one(sig, 'module_name')}: a function module has one output, "
                         f"found {len(outs)} (is it a proc?)")
    pipe = _one(sig, "pipeline", {}) or {}
    ctl = _one(pipe, "pipeline_control", {}) or {}
    valid = _one(ctl, "valid", {}) or {}
    reset = _one(sig, "reset", {}) or {}
    return FnModule(
        module=_one(sig, "module_name"), inputs=ins, output=outs[0],
        clock=_one(sig, "clock_name") or "clk",
        reset=_one(reset, "name") if reset else None,
        reset_active_low=bool(_one(reset, "active_low", False)) if reset else False,
        latency=int(_one(pipe, "latency", 0) or 0),
        input_valid=_one(valid, "input_name") if valid else None,
        output_valid=_one(valid, "output_name") if valid else None)


_DIM = re.compile(r"\[(-?\d+):(-?\d+)\]")


def _dims(a: ApiArg):
    """[(first index, step, length)] of an unpacked argument, outermost first."""
    out = []
    for left, right in _DIM.findall(a.dims):
        left, right = int(left), int(right)
        out.append((left, 1 if right >= left else -1, abs(right - left) + 1))
    return out


def _loops(a: ApiArg, body: str) -> List[str]:
    """Nested loops over every element of unpacked *a*. *body* uses `{idx}`
    (the SV index, e.g. `[k0][k1]`) and `{off}` (the element's bit offset).

    XLS flattens an array with element 0 in the low bits, and each element
    the same way in turn: element (k0, k1, ...) of an array whose element is
    W bits sits at ((k0 * n1 + k1) * n2 + ...) * W."""
    dims = _dims(a)
    idx = "".join(
        f"[{(f'{l} + k{i}' if l else f'k{i}') if st > 0 else f'{l} - k{i}'}]"
        for i, (l, st, _) in enumerate(dims))
    flat = "k0"
    for i, (_, _, n) in enumerate(dims[1:], start=1):
        flat = f"({flat}) * {n} + k{i}"
    off = f"({flat}) * {a.bits}"
    out, pad = [], "        "
    for i, (_, _, n) in enumerate(dims):
        out.append(f"{pad}for (int k{i} = 0; k{i} < {n}; k{i}++)")
        pad += "    "
    out.append(pad + body.format(idx=idx, off=off))
    return out


def _pack(a: ApiArg, port: str) -> List[str]:
    """Statements that put argument *a* on its port's queue."""
    if not a.dims:
        return [f"        q_{port}.push_back({a.name});"]
    return _loops(a, f"p_{port}[{{off}} +: {a.bits}] = {a.name}{{idx}};") + \
        [f"        q_{port}.push_back(p_{port});"]


def xls_binding_sv(api: FnApi, mods: Dict[str, FnModule], period: int = 10,
                   reset_cycles: int = 4, timeout_cycles: int = 100000) -> str:
    n = api.name
    o = [_HEADER.format(task="fw.hdl.api.XlsBinding", src=f"{n} and the XLS signatures"),
         "// Level `rtl` (and `gates`): the API is answered by the XLS modules, through",
         "// a transactor on each module's pins. Latency and port names come from",
         "// the XLS signatures, so a change of pipeline depth changes nothing here",
         "// by hand.", ""]
    for f in api.functions:
        m = mods[f.module]
        if m.input_valid is None or m.output_valid is None:
            raise ValueError(f"{m.module}: generated without valid signals; set Codegen's "
                             f"input_valid_signal and output_valid_signal")
        if len(m.inputs) != len(f.args):
            raise ValueError(f"{m.module}: {len(m.inputs)} input ports for {len(f.args)} "
                             f"arguments of {f.path}")
        rw = m.output[1]
        o += [f"// {f.path} -> module {m.module}, latency {m.latency}",
              f"interface {m.module}_xtor_if (input bit clk, input bit rst);"]
        o += [f"    bit [{w - 1}:0] {port};" for port, w in m.inputs]
        o += [f"    bit {m.input_valid};",
              f"    bit [{rw - 1}:0] {m.output[0]};",
              f"    bit {m.output_valid};", ""]
        o += [f"    bit [{w - 1}:0] q_{port}[$];   // calls not yet presented"
              for port, w in m.inputs]
        o += [f"    bit [{rw - 1}:0] results[int unsigned];   // by call number",
              "    int unsigned issued, collected;", "",
              "    // Present one queued call per cycle; collect results in order.",
              "    always @(posedge clk) begin",
              "        if (rst) begin",
              f"            {m.input_valid} <= 1'b0;",
              "        end else begin"]
        first = m.inputs[0][0] if m.inputs else None
        if first:
            o += [f"            if (q_{first}.size() != 0) begin",
                  f"                {m.input_valid} <= 1'b1;"]
            o += [f"                {port} <= q_{port}.pop_front();" for port, _ in m.inputs]
            o += ["            end else begin",
                  f"                {m.input_valid} <= 1'b0;",
                  "            end"]
        o += [f"            if ({m.output_valid}) begin",
              f"                results[collected] = {m.output[0]};",
              "                collected++;",
              "            end",
              "        end",
              "    end", ""]
        sig_args = [f"input {a.decl()}" for a in f.args] + [f"output {f.ret.decl()}"]
        o += [f"    task automatic call({', '.join(sig_args)});",
              "        int unsigned t = issued++;"]
        o += [f"        bit [{w - 1}:0] p_{port};" for a, (port, w) in zip(f.args, m.inputs)
              if a.dims]
        if f.ret.dims:
            o.append(f"        bit [{rw - 1}:0] r;")
        for a, (port, _) in zip(f.args, m.inputs):
            o += _pack(a, port)
        o.append("        while (!results.exists(t)) @(posedge clk);")
        if f.ret.dims:
            o.append("        r = results[t];")
            o += _loops(f.ret, f"result{{idx}} = r[{{off}} +: {f.ret.bits}];")
        else:
            o.append("        result = results[t];")
        o += ["        results.delete(t);",
              "    endtask",
              "endinterface", ""]

    o += [f"package {n}_xls_pkg;",
          f"    // The bridge: the API, answered by the transactor interfaces.",
          f"    class {n}_xls implements {api.pkg}::{n};"]
    o += [f"        virtual {mods[f.module].module}_xtor_if {f.name}_if;" for f in api.functions]
    for f in api.functions:
        o += [f"        virtual {_task_sig(f)};",
              f"            {f.name}_if.call({_call_args(f)});",
              "        endtask"]
    o += ["    endclass", "endpackage", ""]

    o += [f"module {n}_harness;",
          "    bit clk = 1'b0;",
          "    bit rst = 1'b1;",
          f"    always #{period // 2} clk = ~clk;",
          "    initial begin",
          f"        repeat ({reset_cycles}) @(posedge clk);",
          "        rst <= 1'b0;",
          "    end", ""]
    if timeout_cycles:
        o += ["    // A call that never completes fails the run instead of stalling it.",
              "    initial begin",
              f"        repeat ({timeout_cycles}) @(posedge clk);",
              f"        $fatal(1, \"{n}_harness: timeout after {timeout_cycles} cycles\");",
              "    end", ""]
    for f in api.functions:
        m = mods[f.module]
        o.append(f"    {m.module}_xtor_if {f.name}_if (.clk(clk), .rst(rst));")
        conns = [f".{m.clock}(clk)"]
        if m.reset:
            conns.append(f".{m.reset}({'!rst' if m.reset_active_low else 'rst'})")
        conns += [f".{p}({f.name}_if.{p})" for p, _ in m.inputs]
        conns += [f".{m.input_valid}({f.name}_if.{m.input_valid})",
                  f".{m.output[0]}({f.name}_if.{m.output[0]})",
                  f".{m.output_valid}({f.name}_if.{m.output_valid})"]
        o += [f"    {m.module} u_{f.name} (", "        " + ",\n        ".join(conns), "    );", ""]
    o += ["    initial begin",
          f"        automatic {n}_xls_pkg::{n}_xls x = new();"]
    o += [f"        x.{f.name}_if = {f.name}_if;" for f in api.functions]
    o += [f"        {api.pkg}::bind_api(x);",
          "    end",
          "endmodule", ""]
    return "\n".join(o)
